# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - new_main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a8c17af1-c64e-438d-b3bc-99e9651a1433'
  imageRepository: 'dstncalc'
  containerRegistry: 'containerregistry4pd7i.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'containerregistry4pd7i1162fee2-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |	
        echo VITE_MAPBOX_TOKEN="$(VITE_MAPBOX_TOKEN)" >> /home/vsts/work/1/s/.env
        echo VITE_API_AUTH0_DOMAIN="$(VITE_API_AUTH0_DOMAIN)" >> /home/vsts/work/1/s/.env
        echo VITE_API_AUTH0_CLIENT_ID="$(VITE_API_AUTH0_CLIENT_ID)" >> /home/vsts/work/1/s/.env
        echo VITE_API_AUTH0_AUDIENCE="$(VITE_API_AUTH0_AUDIENCE)" >> /home/vsts/work/1/s/.env
        echo VITE_API_USER_HISTORY_API_URL="$(VITE_API_USER_HISTORY_API_URL)" >> /home/vsts/work/1/s/.env
        echo VITE_API_USER_HISTORY_SCHEMA="$(VITE_API_USER_HISTORY_SCHEMA)" >> /home/vsts/work/1/s/.env
        echo "VITE_AZURE_SAS_TOKEN=$(VITE_AZURE_SAS_TOKEN)" >> /home/vsts/work/1/s/.env
        echo VITE_STORAGE_ACCOUNT_NAME="$(VITE_STORAGE_ACCOUNT_NAME)" >> /home/vsts/work/1/s/.env
        echo VITE_CONTAINER_NAME="$(VITE_CONTAINER_NAME)" >> /home/vsts/work/1/s/.env
        echo VITE_NCALC_API_URL="$(VITE_NCALC_API_URL)" >> /home/vsts/work/1/s/.env
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'precisionsustainableagdstncalc-3980.production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
